### ISSUE TITLE
IStrategy.initialGameConditions called on the same instance for each player

### ISSUE THREAD

**Issue by Thediabloman** [skazzaks/hanabi-ai#1]
Not sure if this is a bug, but in the private initialize method initialGameConditions is called several times. Is each player not supposed to have individual instances of the strategy?

**Comment by skazzaks** [comment]
Hey - thanks for your comment.

This is called once per each player. Each player then fills out the IStrategy interface with the logic for their player, including the logic for 'initialGameConditions'. Right now the system only really supports one player that is multiplied x times, since I figured 1) this is a cooperative game and 2) all optimal players would be using the same strategy.

I hope that answers your question!

**Comment by Thediabloman** [comment]
I agree that each player should use the same strategy, only problem is that
only one instance of IStrategy is ever instantiated, line 290 of
GameManager. Then each player is created with that instance of the strategy
and initialGameConditions is called for each player, but still on the same
instance. This would make it impossible to have any sort of internal memory
for each player, as the same instance of IStrategy is holding it for all
players.

**Comment by skazzaks** [comment]
Aha! I see what you mean. Good catch. I'll try to get that fixed up soon.

**Comment by Thediabloman** [comment]
I did this, which fixed it:

```
private void initialize(String aiClassName, String aiClassLocation, int numPlayers){

    _deck = new Deck();
    // 2-3 players: 5 cards, 4-5 players: 4 cards
    int startingCards = (numPlayers == 2 || numPlayers == 3) ? 5 : 4; 

    // Setup the Gameboard
    _board = new GameBoard();

    // Setup the players
    for(int i = 0; i < numPlayers; i++){
        IStrategy strategy = null;
        try 
        {
            strategy = loadInStrategy();
        }
        catch (Exception e) {
            System.out.println("Could not load in strategy file!");
            e.printStackTrace();
        }


        Player p = new Player(_deck, strategy, startingCards, i);
        _players.add(p);
        strategy.initialGameConditions(p, _numPlayers, startingCards, _numTips);
    }
}

private Class _loadedClass = null; 
private IStrategy loadInStrategy() throws ClassNotFoundException,
IllegalAccessException,
InstantiationException {
    if (_loadedClass != null) return (IStrategy)_loadedClass.newInstance();
    ClassLoader parentClassLoader = MyClassLoader.class.getClassLoader();
    MyClassLoader classLoader = new MyClassLoader(parentClassLoader);
    _loadedClass = classLoader.loadClass(_aiClassName, "file:" + _aiClassLocation);
    return (IStrategy) _loadedClass.newInstance();
}
```

**Comment by skazzaks** [comment]
I did the same thing in the code and checked it in. Thanks!
